# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.15.0-browsers
    steps:
      - checkout
      - restore_node_cache
      - check_build_environment
      - run: yarn install
      - save_node_cache
      - run: yarn build
  test:
    docker:
      - image: circleci/node:8.15.0-browsers
    steps:
      - run: echo TODO!

  deploy:
    docker:
      - image: circleci/node:8.15.0-browsers
    steps:
      - checkout
      - restore_node_cache
      - check_build_environment
      - run: yarn install
      - run: yarn deploy --project machi-aruki-stamp-ebook-dev --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop

commands:
  check_build_environment:
    steps:
      - run: node -v
      - run: npm -v
      - run: yarn -v
      - run: pwd
      - run: find . -maxdepth 1 -type d | xargs ls -la

  # https://circleci.com/docs/ja/2.0/caching/#yarn-node
  restore_node_cache:
    steps:
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

  save_node_cache:
    steps:
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
